name: Build Android APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Generate Gradle wrapper (8.7)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7
          arguments: wrapper

      - name: Build Debug APK
        env:
          # Set these in: Repo → Settings → Secrets and variables → Actions
          FAL_KEY: ${{ secrets.FAL_KEY }}
          PREVIEW_MODEL_SLUG: ${{ secrets.PREVIEW_MODEL_SLUG }}   # e.g., fal-ai/flux-schnell
          FINAL_MODEL_SLUG: ${{ secrets.FINAL_MODEL_SLUG }}       # e.g., fal-ai/flux-pro
        run: |
          chmod +x ./gradlew
          ./gradlew --version
          ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
